host: 127.0.0.1
port: 4000

title: "Chimera Linux"
markdown: kramdown
highlighter: rouge

permalink: /news/:year/:month/:title.html

kramdown:
  parse_block_html: true

plugins:
  - jekyll-redirect-from

social_links:
  - ["irc", "IRC chat", "https://webchat.oftc.net/?channels=#chimera-linux"]
  - ["matrix", "Matrix chat", "https://matrix.to/#/%23chimera-linux:matrix.org"]
  - ["reddit", "Chimera Linux Reddit", "https://www.reddit.com/r/chimeralinux"]
  - ["mastodon", "Chimera Linux Mastodon", "https://floss.social/@chimera_linux"]

collections:
  docs:
    output: true

pkgs_link: "https://pkgs.chimera-linux.org"
buildbot_link: "https://build.chimera-linux.org"
